# Generated by Django 2.2.28 on 2023-10-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyClubuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, verbose_name='user Email')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Venue name')),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=50, verbose_name='zip code')),
                ('phone', models.CharField(max_length=20, verbose_name='contact no')),
                ('web', models.URLField(verbose_name='website')),
                ('email_address', models.EmailField(max_length=254, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Event name')),
                ('event_date', models.DateField(verbose_name='Event date')),
                ('manager', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('attendes', models.ManyToManyField(blank=True, to='app1.MyClubuser')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Venue')),
            ],
        ),
    ]
